{% set name = "practicalsparql" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/practicalSPARQL-{{ version }}.tar.gz
  sha256: 1b0d9c3c5421743ffb5c05afadae45a71aef5f852b5269dcd3bd2b8066e4b2f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sparqlwrapper
    - rdflib
    - numpy

test:
  imports:
    - practicalSPARQL
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hassanhajj910/practicalsparql
  summary: Small wrapper to simplify the interaction with SPARQL endpoints. Built on top of sparqlwrapper and RDFlib
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/hassanhajj910/practicalsparql

extra:
  recipe-maintainers:
    - hassanhajj910
